name: Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish rbxl
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Build rbxm
        run: rojo build -o Framework.rbxm build.project.json
      
      - name: Publish to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} Framework.rbxm
        shell: bash
  release:
    name: Release to wally
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      
      - name: Login to wally
        run: wally login --token ${{ secrets.WALLY_AUTH }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install toml library
        run: pip install toml

      - name: Modify wally.toml
        run: |
          python -c "
          import toml

          with open('wally.toml', 'r') as file:
              data = toml.load(file)

          data['package']['version'] = '${{ github.event.release.tag_name }}'

          with open('wally.toml', 'w') as file:
              toml.dump(data, file)
          "

      - name: Publish to wally
        run: wally publish